### ISSUE TITLE
Soo there's an error

### ISSUE THREAD

**Issue by ElChez** [JulianR0/BDefSaveEditor#2]
So basically I was trying to mess around with the starting wave, but an error isn't letting me do it.
![image](https://user-images.githubusercontent.com/118816390/203304457-a75a2a2e-c90e-474e-aba6-5cc6c96aa329.png)

**Comment by JulianR0** [comment]
Base Defense got an update that changed the structure of the save file. This unfortunately means that the tool is unusuable until I update it. Hopefully it won't take long.

**Comment by JulianR0** [comment]
Okay, I've been working on it for the past few days. I have updated the tool to use the new format and it should work now.

Check the new v0.3.5 release, and let me know if it's all fine.

**Comment by ElChez** [comment]
It's all working now! Thanks for fixing the issue :D
